version: '3'
services:
  mongodb11:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: monitor_poly
    ports:
      - "27017:27017"

  parser11:
    build:
      context: ./
      dockerfile: Dockerfile.parser
    container_name: parser11
    restart: always
    command: bash -c "python parser.py"
    volumes:
      - .:/parser
    depends_on:
      - mongodb11

  bot11:
    build:
      context: ./
      dockerfile: Dockerfile.bot
    container_name: bot11
    restart: always
    command: bash -c "python bot.py"
    volumes:
      - .:/bot
    depends_on:
      - mongodb11
